<?php
/**
 * Created by PhpStorm.
 * User: qiangbi
 * Date: 17-3-16
 * Time: 下午5:44
 */
namespace app\index\model;

use think\Config;
use think\Model;
use think\Url;

class Link extends Model
{
        public function initialize()
        {
            parent::initialize(); // TODO: Change the autogenerated stub
            //后置操作 添加完后修改_url
            Link::event("after_insert",function($link){
                $link_url= urldecode(Config::get("emailDomain.domain").Url::build("Unsubscribeemail/linkJump","link_id=".$link->id."&record_id={{id}}"));
                self::save(["link_url"=>$link_url],["id"=>$link->id]);
            });
        }
}